// Per-presentation history. Every successful Share records an entry
// keyed by the recipient verifier's DID (or `did:elabify:open` when the
// holder shared without a scanned verifier request — the "anyone with
// the QR" case). The Apps tab "Connected verifiers" section reads from
// here.
//
// Phase 0 storage: UserDefaults JSON. Same layer as credentials +
// nicknames so a Reset Wallet wipes everything together.

import Foundation

struct VerifierHistoryEntry: Codable, Identifiable, Sendable {
    let verifierDid: String
    let verifierName: String?
    /// Display nickname for `did:elabify:open` (the open-share path).
    /// Generated by the recorder; not user-editable for now.
    let label: String
    let credentialId: String
    let credentialSchema: String
    let disclosedKeys: [String]
    let lastUsedAt: Int64

    var id: String { "\(verifierDid)/\(credentialId)/\(lastUsedAt)" }
}

enum VerifierHistory {

    private static let key = "verifierHistory.v1"

    static func all() -> [VerifierHistoryEntry] {
        guard let data = UserDefaults.standard.data(forKey: key),
              let entries = try? JSONDecoder().decode([VerifierHistoryEntry].self, from: data) else {
            return []
        }
        return entries
    }

    /// Group by verifier DID, sorted by most-recent.
    static func groupedByVerifier() -> [(verifierDid: String, verifierName: String?, label: String, entries: [VerifierHistoryEntry])] {
        var buckets: [String: [VerifierHistoryEntry]] = [:]
        for e in all() {
            buckets[e.verifierDid, default: []].append(e)
        }
        let groups = buckets.map { (did, list) -> (String, String?, String, [VerifierHistoryEntry]) in
            let sorted = list.sorted(by: { $0.lastUsedAt > $1.lastUsedAt })
            let first = sorted.first!
            return (did, first.verifierName, first.label, sorted)
        }
        return groups.sorted(by: { ($0.3.first?.lastUsedAt ?? 0) > ($1.3.first?.lastUsedAt ?? 0) })
    }

    static func record(
        verifierDid: String,
        verifierName: String?,
        label: String,
        credentialId: String,
        credentialSchema: String,
        disclosedKeys: [String],
        at nowSec: Int64 = Int64(Date().timeIntervalSince1970)
    ) {
        var entries = all()
        entries.insert(
            VerifierHistoryEntry(
                verifierDid: verifierDid,
                verifierName: verifierName,
                label: label,
                credentialId: credentialId,
                credentialSchema: credentialSchema,
                disclosedKeys: disclosedKeys,
                lastUsedAt: nowSec
            ),
            at: 0
        )
        // Keep the latest 200 entries.
        if entries.count > 200 { entries = Array(entries.prefix(200)) }
        if let data = try? JSONEncoder().encode(entries) {
            UserDefaults.standard.set(data, forKey: key)
        }
    }

    static func reset() {
        UserDefaults.standard.removeObject(forKey: key)
    }
}
